# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerapp', '0002_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
