# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerapp', '0003_auto_20180124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='My Slogan', max_length=500),
            preserve_default=False,
        ),
    ]
